services:
  - type: web
    name: jusic-crm
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20.18.0"
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
